### ISSUE TITLE
数据更新后，接口查询数据未刷新

### ISSUE THREAD

**Issue by ywstcc** [mss-boot-io/mss-boot-admin#105]
更新租户过期时间后，table列表显示更新，再次点击编辑数据是更新之前的数据。

![892f0fa20946ab783b328a7c4636560e](https://github.com/mss-boot-io/mss-boot-admin/assets/116046347/5daf3545-e17a-4280-b519-8125fb2f7b6d)

![a82ab1ed71152576114c3116566cf171](https://github.com/mss-boot-io/mss-boot-admin/assets/116046347/dd7962e3-ea5b-48ac-8db1-d702be4cd729)

2边显示时间不一致，关闭缓存配置 (queryCache: false) 数据正常。
```
cache:
  queryCache: false
  queryCacheDuration: 1h
  queryCacheKeys:
    - '*'
```
